In [1]:
import tensorflow as tf
import os
import cv2
import imghdr
from matplotlib import pyplot as plt
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, Dropout
from tensorflow.keras.metrics import Precision, Recall, BinaryAccuracy

C:\Users\pp55\AppData\Local\Temp\ipykernel_15628\1393509764.py:4: DeprecationWarning: 'imghdr' is deprecated and slated for removal in Python 3.13
  import imghdr


In [2]:
from tensorflow.keras.layers import concatenate, Input
from tensorflow.keras.models import Model

In [31]:
# Define the image input
image_input = Input(shape=(256, 256, 3), name='image_input')
conv1 = Conv2D(32, (3, 3), activation='relu')(image_input)
conv2 = Conv2D(64, (3, 3), activation='relu')(conv1)
flatten_img = Flatten()(conv2)

In [32]:
# Define the numerical input
numerical_input = Input(shape=(2,), name='numerical_input')
dense1 = Dense(64, activation='relu')(numerical_input)

In [33]:
concatenated = concatenate([flatten_img, dense1])

In [34]:
dense_common = Dense(128, activation='relu')(concatenated)
output = Dense(2, activation='softmax')(dense_common)

In [35]:
model = Model(inputs=[image_input, numerical_input], outputs=output)


In [36]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [37]:
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 image_input (InputLayer)    [(None, 256, 256, 3)]        0         []                            
                                                                                                  
 conv2d_4 (Conv2D)           (None, 254, 254, 32)         896       ['image_input[0][0]']         
                                                                                                  
 conv2d_5 (Conv2D)           (None, 252, 252, 64)         18496     ['conv2d_4[0][0]']            
                                                                                                  
 numerical_input (InputLaye  [(None, 2)]                  0         []                            
 r)                                                                                         

In [4]:
data_dir = 'firetestdata'
img_exts = ['png', 'jpg', 'jpeg']

In [5]:
img_paths = []
num_paths = []

In [6]:
for directory in os.listdir(data_dir):
    for image in os.listdir(os.path.join(data_dir, directory)):
        img_path = os.path.join(data_dir, directory, image)
        try:
            img = cv2.imread(img_path)
            tip = imghdr.what(img_path)
            print(tip)
            if tip != 'png':
                num_paths.append(img_path)
            else:
                img_paths.append(img_path)
        except:
            print('issue with image {}'.format(img_path))

png
None
png
None
png
None
png
None
png
None


In [3]:
imgnp = []

In [7]:
for path in img_paths:
    im = cv2.imread(path)
    resize = tf.image.resize(im, (256, 256))
    imgnp.append(resize)
    

In [10]:
np.shape(imgnp)

(5, 256, 256, 3)

In [20]:
numnp = []

In [21]:
for path in num_paths:
    with open(path) as r:
        nums = list(map(int, r.read().split(' ')))
        numnp.append(nums)

In [55]:
numnp = np.array(numnp)

In [39]:
target = [1, 1, 1, 1, 1]
target = np.array(target)

In [57]:
dataset = []
imlist = list(map(lambda x : x/255, imgnp))
nulist = list(map(lambda y : y/120, numnp))
print(imlist)
print(nulist)
dataset.append(imlist)
dataset.append(nulist)


[<tf.Tensor: shape=(256, 256, 3), dtype=float32, numpy=
array([[[0.20888768, 0.30236146, 0.2458204 ],
        [0.17303683, 0.23540327, 0.1693527 ],
        [0.0779048 , 0.09105536, 0.07677026],
        ...,
        [0.09090839, 0.14630055, 0.10104885],
        [0.20400535, 0.2905599 , 0.21694623],
        [0.10896283, 0.14421435, 0.10165154]],

       [[0.12207175, 0.18194364, 0.12959129],
        [0.06677294, 0.09692   , 0.04401425],
        [0.04559446, 0.03238071, 0.03875326],
        ...,
        [0.09719621, 0.14107163, 0.1286377 ],
        [0.17458783, 0.2575559 , 0.1842716 ],
        [0.12473671, 0.18408395, 0.13498919]],

       [[0.06274126, 0.07513499, 0.05521264],
        [0.06466136, 0.08601888, 0.06928471],
        [0.07889811, 0.10176355, 0.07889811],
        ...,
        [0.05764878, 0.06454217, 0.07182617],
        [0.10284544, 0.15574831, 0.10361902],
        [0.21596679, 0.29135025, 0.21064405]],

       ...,

       [[0.1972637 , 0.238478  , 0.185713  ],
        [0.0

In [58]:
dataset

[[<tf.Tensor: shape=(256, 256, 3), dtype=float32, numpy=
  array([[[0.20888768, 0.30236146, 0.2458204 ],
          [0.17303683, 0.23540327, 0.1693527 ],
          [0.0779048 , 0.09105536, 0.07677026],
          ...,
          [0.09090839, 0.14630055, 0.10104885],
          [0.20400535, 0.2905599 , 0.21694623],
          [0.10896283, 0.14421435, 0.10165154]],
  
         [[0.12207175, 0.18194364, 0.12959129],
          [0.06677294, 0.09692   , 0.04401425],
          [0.04559446, 0.03238071, 0.03875326],
          ...,
          [0.09719621, 0.14107163, 0.1286377 ],
          [0.17458783, 0.2575559 , 0.1842716 ],
          [0.12473671, 0.18408395, 0.13498919]],
  
         [[0.06274126, 0.07513499, 0.05521264],
          [0.06466136, 0.08601888, 0.06928471],
          [0.07889811, 0.10176355, 0.07889811],
          ...,
          [0.05764878, 0.06454217, 0.07182617],
          [0.10284544, 0.15574831, 0.10361902],
          [0.21596679, 0.29135025, 0.21064405]],
  
         ...,
  
     

In [60]:
model.fit(inputs=[dataset, target], epochs=10, batch_size=1)

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "c:\machinelearning\a66\.venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\pp55\AppData\Local\Temp\ipykernel_15628\1469903299.py", line 1, in <module>
    model.fit(inputs=[dataset, target], epochs=10, batch_size=1)
  File "c:\machinelearning\a66\.venv\Lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "c:\machinelearning\a66\.venv\Lib\site-packages\keras\src\utils\traceback_utils.py", line 67, in error_handler
    filtered_tb = _process_traceback_frames(e.__traceback__)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Model.fit() got an unexpected keyword argument 'inputs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\machinelearning\a66\.venv\Lib\site-packages\IPyth

In [ ]:
def create_cnn(width, height, depth, filters=(16, 32, 64), regress=False):
	# initialize the input shape and channel dimension, assuming
	# TensorFlow/channels-last ordering
	inputShape = (height, width, depth)
	chanDim = -1
	# define the model input
	inputs = Input(shape=inputShape)
	# loop over the number of filters
	for (i, f) in enumerate(filters):
		# if this is the first CONV layer then set the input
		# appropriately
		if i == 0:
			x = inputs
		# CONV => RELU => BN => POOL
		x = Conv2D(f, (3, 3), padding="same")(x)
		x = Activation("relu")(x)
		x = BatchNormalization(axis=chanDim)(x)
		x = MaxPooling2D(pool_size=(2, 2))(x)
		# flatten the volume, then FC => RELU => BN => DROPOUT
    x = Flatten()(x)
	x = Dense(16)(x)
	x = Activation("relu")(x)
	x = BatchNormalization(axis=chanDim)(x)
	x = Dropout(0.5)(x)
	# apply another FC layer, this one to match the number of nodes
	# coming out of the MLP
	x = Dense(4)(x)
	x = Activation("relu")(x)
	# check to see if the regression node should be added
	if regress:
		x = Dense(1, activation="linear")(x)
	# construct the CNN
	model = Model(inputs, x)
	# return the CNN
	return model